[package]
name = "snow-ui-web-example"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
snow-ui = { git = "https://github.com/snow-ui-rs/snow-ui.git" }
snow-ui-macros = { git = "https://github.com/snow-ui-rs/snow-ui.git" }
wasm-bindgen = "0.2"
